
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
    
- name: Install qemu
  apt:
   name:
     - ntpdate
     - git
     - htop
     - tmux
     - vim
     - iotop
     - bridge-utils
     - cpu-checker
     - dnsmasq
     - golang 
     - zip 
     - unzip 
   state: latest

- name: unistall nano
  package:
    name: nano 
    state: absent

- name: terraform install
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{version}}/terraform_{{version}}_{{platform}}.zip
    dest: /usr/bin
    remote_src: True

- name: turn one automatic security  pdates 
  package:
    name: unattended-upgrades
    state: present

- name: copy 30auto-upgrades 
  copy:
    src: 30auto-upgrades.tmpl
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

